Added string functions library
nandlabs/go-commons pull request #93
Opened 2023-10-01 05:23 UTC by MEHUL25

solves #3 Create Str Functions Library

Added string functions to perform different operations.

2023-10-01 05:24 UTC, MEHUL25 commented
closes #3

2023-10-05 12:31 UTC, nandagopalan requested changes
Overall Looks good Needs some minor signature fixes and logic changes

2023-10-05 12:31 UTC, nandagopalan commented on string/string.go
> +func Concat(s1, s2 string) string {
May be this can the function signature can allow  the variable argument list.
func Concat(s ... string) string {
...code
}

2023-10-05 12:31 UTC, nandagopalan commented on string/string.go
> +func Join(strs []string, separator string) string {
May be this can the function signature can allow the variable argument list.
func Join( separator string,s ... string) {
...code
}

2023-10-05 12:31 UTC, nandagopalan commented on string/string.go
> +		reversed[j] = runes[i]
may be avoid creating a reversed rune array for a new length and instead use 

 for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 { 
         runes[i], runes[j] = runes[j], runes[i] 
    } 

 return string(runes)

2023-10-10 07:24 UTC, MEHUL25 commented
Addressed review comments. @nandagopalan please go through it and confirm it.

2024-02-15 22:08 UTC, nandagopalan commented
Requirement removed  in favour of builtin function

2024-02-15 22:08 UTC, closed without merging